name: Publish
on: [pull_request]
jobs:
  generate-link:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 👀
        uses: actions/checkout@v3

      - name: Node setup 👷
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Build 🛠
        run: npm i && npm run build

      - name: Get PR number
        run: echo "::set-output name=num::$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')"
        id: pr-number

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: staging # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
          target-folder: ${{ steps.pr-number.outputs.num }}
